services:
  - type: web
    name: cairspa
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: rewrite
        source: /services/*
        destination: /index.html
      - type: rewrite
        source: /areas/*
        destination: /index.html
      - type: rewrite
        source: /blog/*
        destination: /index.html
