// Vercel serverless function: POST /api/match
// Matches a visitor's own description of their concern to a CAIR SPA treatment
// using TypeSafe (Jev). Requires the TYPESAFE_API_KEY environment variable in Vercel.
// Generated by site-src/build.mjs — edit the template, not api/match.js.

const CATALOG = [
 {
  "slug": "botox",
  "name": "Neurotoxin",
  "blurb": "Soften frown lines, forehead lines and crow's feet",
  "goodFor": [
   "Frown lines between the brows (the \"11s\")",
   "Horizontal forehead lines",
   "Crow's feet around the eyes",
   "Bunny lines on the sides of the nose",
   "A subtle brow lift",
   "Chin dimpling or an \"orange peel\" chin",
   "Softening a gummy smile",
   "Preventive treatment for early expression lines"
  ]
 },
 {
  "slug": "dermal-fillers",
  "name": "Fillers & HA Injectables",
  "blurb": "HA fillers for lips, cheeks, jawline and skin boosters",
  "goodFor": [
   "Thin lips or uneven lip shape",
   "Flattened or hollow cheeks",
   "A softer or less defined jawline",
   "A recessed or weak-looking chin",
   "Under-eye hollows and tired-looking eyes",
   "Smile lines and marionette lines",
   "Dull, dehydrated or crepey skin (skin boosters)",
   "Fine lines and rough skin texture (skin boosters)"
  ]
 },
 {
  "slug": "sculptra",
  "name": "Sculptra",
  "blurb": "Collagen stimulator for gradual, natural volume",
  "goodFor": [
   "Overall facial volume loss with age",
   "Hollow temples",
   "Flattened cheeks or midface",
   "Smile lines and deeper folds",
   "Softening jawline definition",
   "Thinning or less firm skin",
   "People who prefer gradual, subtle change"
  ]
 },
 {
  "slug": "prp-hair-restoration",
  "name": "PRP / PRF Hair Restoration",
  "blurb": "Platelet scalp injections for thinning hair",
  "goodFor": [
   "Early to moderate pattern hair thinning in men",
   "Diffuse thinning or a widening part in women",
   "A receding hairline in its early stages",
   "Hair that has become finer or weaker",
   "Supporting results alongside other hair-loss treatments",
   "People who prefer a non-surgical, low-downtime option"
  ]
 },
 {
  "slug": "prf-under-eye",
  "name": "PRF Under-Eye Rejuvenation",
  "blurb": "Natural under-eye refresh using your own platelets",
  "goodFor": [
   "Thin or crepey under-eye skin",
   "Fine lines below the eyes",
   "Mild under-eye hollowness",
   "Dark circles related to thin skin",
   "A tired or dull look around the eyes",
   "People who prefer a treatment made from their own blood"
  ]
 },
 {
  "slug": "facial",
  "name": "Customized Facial",
  "blurb": "Deep cleanse, exfoliation and hydration for your skin",
  "goodFor": [
   "Dull or tired-looking skin",
   "Clogged pores and blackheads",
   "Dry or dehydrated skin",
   "Rough or uneven texture",
   "Oily or congested areas",
   "Prepping skin before an event",
   "Maintenance between advanced treatments"
  ]
 },
 {
  "slug": "rf-microneedling",
  "name": "Microneedling",
  "blurb": "Microneedling and RF microneedling for texture and scars",
  "goodFor": [
   "Acne scars",
   "Fine lines and wrinkles",
   "Enlarged pores",
   "Rough or uneven texture",
   "Mild skin laxity",
   "Dullness and uneven tone",
   "Some types of stretch marks"
  ]
 },
 {
  "slug": "skin-rejuvenation",
  "name": "Skin Rejuvenation",
  "blurb": "A combined plan for tone, texture and glow",
  "goodFor": [
   "Dull, tired-looking skin",
   "Uneven tone and sun spots",
   "Redness",
   "Rough texture and enlarged pores",
   "Fine lines and wrinkles",
   "Acne scars",
   "Mild volume loss",
   "People who want one coordinated plan"
  ]
 },
 {
  "slug": "aerolase",
  "name": "Aerolase Laser",
  "blurb": "One gentle laser for hair, veins, acne and spots",
  "goodFor": [
   "Unwanted hair on the face or body",
   "Small benign skin tags",
   "Spider veins and small facial or leg veins",
   "Active acne and acne-related redness",
   "Melasma, as part of a conservative plan",
   "Sun spots, age spots and other benign pigmented lesions",
   "People with lighter or darker skin tones looking for a gentle laser option"
  ]
 },
 {
  "slug": "laser-hair-removal",
  "name": "Laser Hair Removal",
  "blurb": "Long-term hair reduction for all skin tones",
  "goodFor": [
   "Underarms",
   "Bikini line",
   "Legs and arms",
   "Upper lip, chin and face",
   "Back and chest",
   "Ingrown hairs and razor bumps",
   "People who want to shave or wax less often"
  ]
 },
 {
  "slug": "skin-tag-removal",
  "name": "Skin Tag Removal",
  "blurb": "Quick laser removal of small benign skin tags",
  "goodFor": [
   "Skin tags on the neck",
   "Skin tags in the underarms",
   "Tags under the breasts or in the groin folds",
   "Small tags on the eyelid area, when appropriate",
   "Tags that catch on jewelry, collars or straps",
   "Tags that are irritated by shaving",
   "People who want a quick, low-downtime option"
  ]
 },
 {
  "slug": "vein-treatment",
  "name": "Vein Removal",
  "blurb": "Laser treatment for spider and small facial veins",
  "goodFor": [
   "Spider veins on the legs",
   "Small broken blood vessels on the face",
   "Visible veins around the nose and cheeks",
   "Diffuse facial redness from small vessels",
   "Small red or purple vessels on the chin",
   "People who prefer a needle-free option"
  ]
 },
 {
  "slug": "acne-treatment",
  "name": "Acne Treatment",
  "blurb": "Laser care for active acne and post-acne redness",
  "goodFor": [
   "Mild to moderate active acne",
   "Inflamed red breakouts",
   "Redness left behind after breakouts",
   "Acne on the face, chest or back",
   "Hormonal breakouts along the jawline",
   "People of all skin tones looking for a gentle option",
   "Those who want to complement their skincare routine"
  ]
 },
 {
  "slug": "melasma-treatment",
  "name": "Melasma Treatment",
  "blurb": "Conservative laser care to help manage melasma",
  "goodFor": [
   "Brown or gray-brown patches on the cheeks",
   "Melasma on the forehead or upper lip",
   "Pigment that darkened with pregnancy or hormones",
   "Uneven tone that worsens with sun exposure",
   "People willing to commit to daily sun protection",
   "Those looking for a gentle, gradual approach"
  ]
 },
 {
  "slug": "pigmented-lesions",
  "name": "Pigmented Lesions",
  "blurb": "Fade sun spots and age spots with Aerolase",
  "goodFor": [
   "Sun spots on the face",
   "Age spots on the backs of the hands",
   "Brown spots on the chest and shoulders",
   "Freckles you would like to lighten",
   "Uneven tone from past sun exposure",
   "Benign spots confirmed by a provider"
  ]
 },
 {
  "slug": "iv-infusion",
  "name": "IV Therapy",
  "blurb": "Fluids, vitamins and minerals delivered by IV drip",
  "goodFor": [
   "Rehydration after travel or a long day",
   "Recovery support after exercise or outdoor activity",
   "Feeling run down or depleted",
   "Busy schedules that make hydration hard to keep up with",
   "People who prefer a relaxing, supervised wellness break",
   "Adding vitamin and mineral support as part of a wellness routine"
  ]
 },
 {
  "slug": "nad-therapy",
  "name": "NAD+ Therapy",
  "blurb": "Supervised NAD+ infusions as part of a wellness plan",
  "goodFor": [
   "Adults curious about NAD+ as part of a wellness routine",
   "Interest in healthy aging support",
   "People who prefer a medically supervised setting for IV wellness treatments",
   "Guests who already use other wellness services and want to explore NAD+",
   "Those who want honest, evidence-aware guidance before trying a new therapy"
  ]
 },
 {
  "slug": "weight-loss",
  "name": "Medical Weight Loss",
  "blurb": "Medically supervised weight loss programs",
  "goodFor": [
   "Adults who have not reached their goals with diet and exercise alone",
   "Weight-related health concerns your provider wants to address",
   "People who want structured accountability and regular check-ins",
   "Those interested in learning whether GLP-1 medications are appropriate for them",
   "Support with nutrition and sustainable habit changes",
   "Anyone who prefers a medically supervised approach over fad diets"
  ]
 },
 {
  "slug": "thread-lift",
  "name": "Thread Lift",
  "blurb": "Non-surgical lift for mild sagging with dissolvable threads",
  "goodFor": [
   "Mild sagging in the cheeks or midface",
   "Softening jawline definition and jowls",
   "Low or heavy-looking brows",
   "Mild neck laxity",
   "People who want a lift without surgery",
   "Adding support alongside fillers or other treatments"
  ]
 },
 {
  "slug": "exosome-therapy",
  "name": "Exosome Therapy",
  "blurb": "Topical exosome add-on to support skin after treatments",
  "goodFor": [
   "Adding to a microneedling session",
   "Dull or tired-looking skin",
   "Uneven texture",
   "Supporting skin comfort after treatment",
   "People who understand the evidence is still developing"
  ]
 },
 {
  "slug": "hair-transplant",
  "name": "ARTAS Hair Restoration",
  "blurb": "Robotic-assisted FUE hair transplant procedure",
  "goodFor": [
   "Receding hairline",
   "Thinning at the crown",
   "Male pattern hair loss with stable, healthy donor hair",
   "Some cases of female pattern hair loss, after evaluation",
   "People who prefer to avoid a linear donor scar",
   "Those who want to wear their hair shorter in back",
   "Restoring density in areas where hair loss has stabilized"
  ]
 }
];

const TREATMENT_CRITERIA = Object.fromEntries([
  ...CATALOG.map((s) => [s.slug, { treatment: s.name, what: s.blurb, helps_with: s.goodFor }]),
  ['unclear', { what: 'The message is too vague to match, is unrelated to aesthetic or wellness treatments, or asks for something none of the other treatments address.' }],
]);

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });
  const key = process.env.TYPESAFE_API_KEY;
  if (!key) return res.status(503).json({ error: 'Matcher not configured' });

  const concern = String((req.body && req.body.concern) || '').trim().slice(0, 500);
  if (concern.length < 3) return res.status(400).json({ error: 'Please describe your concern' });

  const payload = {
    model: 'jev-latest',
    state: { visitor_message: concern, clinic: 'CAIR SPA, a medical spa in Huntington Beach, CA' },
    questions: {
      treatment: {
        type: 'choice',
        instructions: {
          question: 'Which treatment offered by the clinic best addresses the concern described in `visitor_message`?',
          focus: 'Match the skin, face, hair, body or wellness concern the visitor wants to improve to the single most suitable treatment.',
        },
        criteria: TREATMENT_CRITERIA,
      },
      needs_medical_review: {
        type: 'noul',
        instructions: 'Does `visitor_message` describe a symptom that should be medically evaluated before any cosmetic treatment, such as a mole or spot that is changing, bleeding or itching, sudden or painful swelling, signs of infection, a bad reaction to a previous treatment, or another possible medical problem?',
        criteria: {
          true: 'Describes a possible medical problem or warning sign that needs evaluation first',
          false: 'Describes an ordinary cosmetic or wellness goal',
        },
      },
    },
  };

  try {
    const r = await fetch('https://api.typesafe.ai/v1/systemone', {
      method: 'POST',
      headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(8000),
    });
    if (!r.ok) return res.status(502).json({ error: 'Matcher unavailable' });
    const data = await r.json();
    const t = data.answers.treatment;
    const medical = data.answers.needs_medical_review.noul >= 0.5;

    const ranked = Object.entries(t.probabilities || {})
      .filter(([slug, p]) => slug !== 'unclear' && p >= 0.08)
      .sort((a, b) => b[1] - a[1])
      .map(([slug]) => slug)
      .slice(0, 3);
    const unsure = t.choice === 'unclear' || t.confidence < 0.35;

    res.setHeader('Cache-Control', 'no-store');
    return res.status(200).json({ matches: ranked, unsure, medical, source: 'typesafe' });
  } catch (e) {
    return res.status(502).json({ error: 'Matcher unavailable' });
  }
}
